---
name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@thomasvincent'

      - name: Install dependencies
        run: npm install --production=false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install pyyaml yamllint

      - name: Validate SSM documents
        run: npm run lint

      - name: Update README with script documentation
        run: npm run update-readme

      - name: Create distribution package
        run: npm run package

      - name: Create GitHub release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}