name: Test SSM Scripts

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.yaml'
      - '**.yml'
      - '!.github/**'

jobs:
  test-scripts:
    name: Test Scripts in Sandbox
    runs-on: ubuntu-latest
    # Only run this job if explicitly approved in the PR comments
    if: contains(github.event.pull_request.labels.*.name, 'safe-to-test')
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SANDBOX_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.SANDBOX_ROLE_ARN }}
          role-duration-seconds: 1800
          
      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
          
      - name: Register and test SSM documents
        run: |
          # For each YAML file in the repository
          for file in $(find . -name "*.yaml" -o -name "*.yml" | grep -v "^\.\/\.github"); do
            echo "Processing $file..."
            file_basename=$(basename "$file")
            document_name="Test-$(echo $file_basename | sed 's/\.yaml$\|\.yml$//')-${{ github.run_id }}"
            
            # Convert YAML to JSON for AWS CLI v2 compatibility
            python3 -c "import yaml, json, sys; print(json.dumps(yaml.safe_load(open('$file', 'r'))))" > temp_document.json
            
            # Register document in SSM
            echo "Registering document $document_name..."
            aws ssm create-document \
              --name "$document_name" \
              --document-type "Automation" \
              --content file://temp_document.json
              
            # Document successfully registered
            echo "Document $document_name registered successfully!"
            
            # Clean up after tests
            echo "Cleaning up document $document_name..."
            aws ssm delete-document --name "$document_name"
            rm -f temp_document.json
          done